#Copyright 2018 Juha-Pekka Pulkkinen https://github.com/a1704565 GNU General Public License v3.0
#Vagrantfile - For testing purposes only
#Based on http://terokarvinen.com/2018/automatically-provision-vagrant-virtualmachines-as-salt-slaves

$tscript = <<TSCRIPT
sudo apt-get update
sudo apt-get -y install salt-master salt-minion
echo -e 'master: 127.0.0.1\nid: vagrant001'|sudo tee /etc/salt/minion
sleep 2s
sudo systemctl restart salt-minion.service
sleep 5s
sudo salt-key -yA
TSCRIPT

Vagrant.configure("2") do |config|
 config.vm.box = "bento/ubuntu-16.04"
 config.vm.provision "shell", inline: $tscript
end
